### ISSUE TITLE
ElementCollection seems to only support enums

### ISSUE THREAD

**Issue by Zenith-One** [jcrygier/graphql-jpa#10]
I have an element collection of 'Class' which is used to persist the class name of an object. When the GraphQLSchemaBuilder hits this attribute, it checks to see if it's an enum (which it isn't) and if not, returns null. 

This then causes a null to be passed into the constructor for GraphQLList.

Am I doing something wrong, or is this a bug?

**Comment by stomf** [comment]
I've encountered this as well; can be duplicated by adding

`@ElementCollection(targetClass=String.class) List<String> codas = new ArrayList<String>();`

to the Droid class, which causes the test cases to fail when building the schema.

**Comment by jcrygier** [comment]
Closed....thanks for the contribution @stomf !!!!
