### ISSUE TITLE
Perform & push a release to some maven repository

### ISSUE THREAD

**Issue by timtebeek** [jcrygier/graphql-jpa#20]
With the recent changes by @lestard in #15, #17 & #18 I thought this might be a good time to up the version number and push a release to some Maven repository. That way I can [update my dependency in a downstream project](https://github.com/timtebeek/graphql-jpa-spring-boot-starter/) and release that.

What are your thoughts on this @jcrygier ?

**Comment by jcrygier** [comment]
@timtebeek Bumped to v0.3, pushed to jcenter.  Please let me know if you have any issues.

Thanks!

**Comment by timtebeek** [comment]
Perfect, thanks a lot! :)
