### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by manuel-mauky** [jcrygier/graphql-jpa#29]
Please clarify the license for this project. There is no LICENSE file in the root of the repository.
The only hint I've found was at [bintray](https://bintray.com/jcrygier/maven/GraphQL-JPA/0.3/view/readmore) where it says the license is MIT. 
This is also the license that [graphql-java](https://github.com/graphql-java/graphql-java/blob/master/LICENSE.md) uses. 
However, it would be nice to make the license clear and easy to find.

**Comment by jcrygier** [comment]
Hi...Yes, it is MIT Licensed.  I'll do the work shortly to get a LICENSE file out there as well as some headers on the source files.  I've been traveling lately, so this may take a few days.

**Comment by deinspanjer** [comment]
This issue should be closed.
