### ISSUE TITLE
@GraphQLIgnore does not always ignore unsupported types

### ISSUE THREAD

**Issue by stomf** [jcrygier/graphql-jpa#40]
An exception is thrown if an entity in the JPA model contains an unsupported data type, eg a byteArray:

`java.lang.UnsupportedOperationException: Attribute could not be mapped to GraphQL: field 'data' of entity class 'org.crygier.graphql.model.starwars.Droid'`

It is possible to suppress this exception by adding `@GraphQLIgnore` to the offending field. However this does not work if the entity is referenced by another entity in the model.

Issue can be duplicated by adding 

`@GraphQLIgnore byte[] data; `

to the Droid model; all the test cases fail when trying to build the schema.

**Comment by jcrygier** [comment]
See Pull Request #41.  Thanks!
